

spring:
  application:
    name: StoreService
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
  servlet:
    context-path: /api/v1
